#!/usr/bin/env bash

set +abeuvx

cmd=$1
PROJ_NAME="de-cloudwatch-logs-to-elasticsearch"
PROJ_HOME="/app/${PROJ_NAME}"

display_help() {
    echo "Usage: $0 [option]" >&2
    echo
    echo " Available options:"
    echo "   docker-build          "
    echo "   shell                 "
    echo "   sls-deploy-dev        "
    echo "   logs                  "
    echo
}

cleanup() {
    rm -r *-info certifi chardet elasticsearch idna node_Modules requests requests_aws4auth urllib3
}


case $cmd in

    '-h')
        display_help
        exit 0
        ;;

    'docker-build')
        docker build -t ${PROJ_NAME} .
        ;;

    'shell')
        docker run --rm -it \
        -v $(pwd):${PROJ_HOME}  \
        --env-file=deploy_env \
        ${PROJ_NAME}:latest \
        env
        ;;

    'sls-deploy-dev')
        docker run --rm -it \
        -v $(pwd):${PROJ_HOME} \
        -e AWS_ACCESS_KEY_ID \
        -e AWS_SECRET_ACCESS_KEY \
        -e AWS_SESSION_TOKEN \
        -e AWS_DEFAULT_REGION \
        -e AWS_REGION \
        --env-file=deploy_env \
        ${PROJ_NAME}:latest \
        bash -c " pip3 install -r requirements.txt -t ${PROJ_HOME} && SLS_DEBUG=* sls deploy -v  --force --stage dev" && \
        cleanup
        ;;
      
    'logs')
        shift && \
        export $(cat docker_env) && \
        sls plugin install --name serverless-pseudo-parameters && \
        export AWS_SDK_LOAD_CONFIG=1 && \
        export AWS_PROFILE=harrys-core-development && \
        sls logs -f LogsToElasticSearch -t --stage dev
        ;;

    *)
        echo "Unknown command: $cmd"
        display_help
        exit 1
        ;;

esac

